@eAppointmentServer.WebAPI_HostAddress = http://localhost:5246

POST http://localhost:5246/api/Auth/Login
Accept: application/json
Content-Type: application/json
{
    userNameOrEmail:"admin",
    "password":""
}

###
